// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'exitButton': string;
  'smth': string;
  'wrappExit': string;
}
export const cssExports: CssExports;
export default cssExports;
