// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'login': string;
  'login-form': string;
  'login1': string;
}
export const cssExports: CssExports;
export default cssExports;
