// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'home': string;
  'logo': string;
  'navbar': string;
  'standart': string;
}
export const cssExports: CssExports;
export default cssExports;
